name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'apps/ts-automations/**'
  pull_request:
    paths:
      - 'apps/ts-automations/**'
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: yarn install --frozen-lockfile

      - run: npx nx build ts-automations

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/ts-automations:latest -f apps/ts-automations/Dockerfile .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/ts-automations:latest
