name: publish

on:
  workflow_call:
    inputs:
      app:
        description: 'Nx app name (e.g. ts-automations)'
        required: true
        type: string

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - run: yarn install --frozen-lockfile

      - run: npx nx build ${{ inputs.app }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          npx nx docker:build ${{ inputs.app }} -t ghcr.io/${{ github.repository }}/${{ inputs.app }}:latest

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository }}/${{ inputs.app }}:latest