name: publish-warehouse

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'apps/ts-warehouse/**'
  pull_request:
    paths:
      - 'apps/ts-warehouse/**'

permissions:
  actions: read
  contents: read
  packages: write

jobs:
  publish:
    uses: ./.github/workflows/publish.yml
    with:
      app: ts-warehouse